name: sf-provisioning-poc
on:
  push:
    branches:
      - master
    paths:
      - 'dbscripts/**'

  workflow_dispatch:

jobs:
  sf-provisioning-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repo
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: '3.8.x'
      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_DATABASE: 'DEMO'
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SF_ROLE: 'SYSADMIN'
          SF_WAREHOUSE: 'A1SF_WH_INTERNAL_ETL_XSMALL'
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step-1: installing schemachange"
          pip install schemachange --upgrade
          echo 'Step 2: Running schemachange'
          echo 'account: $SF_ACCOUNT'
          echo 'account: $(SF_ACCOUNT)'
          #echo 'project folder: $PROJECT_FOLDER'
          #echo 'pwd: $pwd'

          #schemachange --help
          #schemachange -f $(PROJECT_FOLDER)/migrations -a $(SF_ACCOUNT) -u $(SF_USERNAME) -r $(SF_ROLE) -w $(SF_WAREHOUSE) -d $(SF_DATABASE) -c $(SF_DATABASE).SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table -v
          #schemachange -f /home/runner/work/sf-provisioning/sf-provisioning/dbscripts -a agilonedev.us-east-1 -u SMUNSWAMY -r SYSADMIN -w A1SF_WH_INTERNAL_ETL_XSMALL -d DEMO -c DEMO.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
          schemachange -f /home/runner/work/sf-provisioning/sf-provisioning/dbscripts -a agilonedev.us-east-1 -u $(SF_USERNAME) -r SYSADMIN -w A1SF_WH_INTERNAL_ETL_XSMALL -d DEMO -c DEMO.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table -v
